/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mm;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form C
     */
     String sql;
     static Socket s;
     static DataInputStream din;
     static DataOutputStream dout;
    public Client() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        mes_txt1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mes_txt2 = new javax.swing.JTextField();
        mes_txt3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        insert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        creat = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        selectbtn = new javax.swing.JButton();
        selectSUM = new javax.swing.JButton();
        SelectOrder = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CLIENT");
        setBackground(new java.awt.Color(0, 153, 153));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(19, 55, 126));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Client Program");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fin/icon/data (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fin/icon/Untitled-1.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(19, 55, 126));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Employees");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel6)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        mes_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes_txt1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(19, 55, 126));
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(19, 55, 126));
        jLabel2.setText("NAME");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(19, 55, 126));
        jLabel3.setText("SALARY");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        insert.setBackground(new java.awt.Color(255, 255, 255));
        insert.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        insert.setForeground(new java.awt.Color(19, 55, 126));
        insert.setText("Insert");
        insert.setToolTipText("");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        update.setForeground(new java.awt.Color(19, 55, 126));
        update.setText("Update");
        update.setMaximumSize(new java.awt.Dimension(70, 23));
        update.setMinimumSize(new java.awt.Dimension(70, 23));
        update.setPreferredSize(new java.awt.Dimension(70, 23));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        creat.setBackground(new java.awt.Color(255, 255, 255));
        creat.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        creat.setForeground(new java.awt.Color(19, 55, 126));
        creat.setText("Create");
        creat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(19, 55, 126));
        delete.setText("Delete");
        delete.setMaximumSize(new java.awt.Dimension(70, 29));
        delete.setMinimumSize(new java.awt.Dimension(70, 29));
        delete.setPreferredSize(new java.awt.Dimension(70, 29));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        selectbtn.setBackground(new java.awt.Color(255, 255, 255));
        selectbtn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        selectbtn.setForeground(new java.awt.Color(19, 55, 126));
        selectbtn.setText("Select");
        selectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectbtnActionPerformed(evt);
            }
        });

        selectSUM.setBackground(new java.awt.Color(255, 255, 255));
        selectSUM.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        selectSUM.setForeground(new java.awt.Color(19, 55, 126));
        selectSUM.setText("Select SUM");
        selectSUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSUMActionPerformed(evt);
            }
        });

        SelectOrder.setBackground(new java.awt.Color(255, 255, 255));
        SelectOrder.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        SelectOrder.setForeground(new java.awt.Color(19, 55, 126));
        SelectOrder.setText("Select Order");
        SelectOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectSUM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(creat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(SelectOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creat)
                .addGap(4, 4, 4)
                .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectSUM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mes_txt1)
                    .addComponent(mes_txt2)
                    .addComponent(mes_txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mes_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mes_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mes_txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
      try{
             String msgout1="";
             String msgout2="";
             String msgout3="";
                          
             msgout1=mes_txt1.getText().trim();
             msgout2=mes_txt2.getText().trim();
             msgout3=mes_txt3.getText().trim();
             long slr_long=new Long(msgout3);
             //------------------ requet SQL  Insert Statement---------------
                 System.out.println("insert : " + slr_long);
             String sql= "INSERT INTO emp"
                       +"(id,nm,slr)"
                       +"VALUES("+msgout1+",'"+msgout2+"',"+slr_long+");";
             
             //------------------Send Requet to Proxy ---------------------------
             
             dout.writeUTF(sql);
           
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_insertActionPerformed

    private void mes_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mes_txt1ActionPerformed
        // TODO add your handlin,g code here:
    }//GEN-LAST:event_mes_txt1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        sql=null;
        try{
             String msgout1="";
             String msgout2="";
             String msgout3="";
             
             msgout1=mes_txt1.getText().trim();
             msgout2=mes_txt2.getText().trim();
             msgout3=mes_txt3.getText().trim();
             if (msgout1.equals(""))
                     {
                       JOptionPane.showMessageDialog(null, "Please enter the number of : id "); 
                     }
             if ((!mes_txt2.getText().equals("")) && (!mes_txt3.getText().equals("")))
             {

             sql= "UPDATE emp SET nm = '"+msgout2+"', slr ="+msgout3+" WHERE id="+msgout1+";";
            System.out.println("requet send: nm :" + sql +"  ---------- id =  " + msgout1);
             dout.writeUTF(sql);
             }
             else if ((!mes_txt2.getText().equals("")) && (mes_txt3.getText().equals("")))
             {
             sql= "UPDATE emp SET nm = '"+msgout2+"' WHERE id="+msgout1+";";
            System.out.println("requet send: nm :" + sql +"  ---------- id =  " + msgout1);
             dout.writeUTF(sql); 
             }
             else if ((mes_txt2.getText().equals("")) && (!mes_txt3.getText().equals("")))
             {
             String sql= "UPDATE emp SET slr = "+msgout3+" WHERE id="+msgout1+";";
            System.out.println("requet send: nm :" + sql +"  ---------- id =  " + msgout1);
            dout.writeUTF(sql);
             }
             else
             {
                 JOptionPane.showMessageDialog(null, "Please enter the name and salary  "); 
             }
             
             
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
         try{
             String msgout1="";
             String msgout2="";
             String msgout3="";
             
             msgout1=mes_txt1.getText().trim();
             msgout2=mes_txt2.getText().trim();
             msgout3=mes_txt3.getText().trim();
             
             
              String sql= "DELETE FROM emp WHERE id=" + msgout1+";";

             
             dout.writeUTF(sql);
            
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_deleteActionPerformed
    
    
    //---------------------------------------------------
    private void selectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectbtnActionPerformed
        // TODO add your handling code here:
       
        // our SQL SELECT query. 
       
        try{
             String msgout1="";
             String msgout2="";
             String msgout3="";
             
             msgout1=mes_txt1.getText().trim();
             msgout2=mes_txt2.getText().trim();
             msgout3=mes_txt3.getText().trim();
        if ((!mes_txt1.getText().equals("")) && (!mes_txt3.getText().equals("")) && (!mes_txt2.getText().equals(""))) 
                {
                    sql= "SELECT id,nm,slr FROM emp where id = "        ///----- select all
                            + msgout1 + "AND nm Like "+ msgout2 +"AND slr = "+msgout3+";";
                    System.out.println("requet send:"+ sql );
                    dout.writeUTF(sql);
                   
                }
        else {
        if ((mes_txt1.getText().equals("")) && (mes_txt3.getText().equals("")) && (mes_txt2.getText().equals(""))) 
               {
                    sql= "SELECT id,nm,slr FROM emp";
                    System.out.println("requet send:" + sql);
                    dout.writeUTF(sql);
                }
        
       
       else if ((!mes_txt1.getText().equals("")) || (!mes_txt2.getText().equals("")) || (!mes_txt3.getText().equals("")) ) 
               {
                      if (!mes_txt2.getText().equals("") &&( (mes_txt1.getText().equals("")) && (mes_txt3.getText().equals("")) )) 
                        {
                             System.out.println(msgout2);
                                sql= "SELECT id,nm,slr FROM emp WHERE nm Like '"
                                 +msgout2+"';";
                             System.out.println("requet send: nm :" + sql);
                             dout.writeUTF(sql);
                         }
                           else if (!mes_txt3.getText().equals("") &&( (mes_txt1.getText().equals("")) && (mes_txt2.getText().equals("")) ) ) 
                            {
                              System.out.println(msgout3);
                              sql= "SELECT id,nm,slr FROM emp WHERE slr = "
                                  +msgout3+";";
                             System.out.println("requet send salary:" + sql);
                             dout.writeUTF(sql);
                            }
                             else if (!mes_txt1.getText().equals("") &&( (mes_txt2.getText().equals("")) && (mes_txt3.getText().equals("")) )) 
                            {
                                System.out.println(msgout1);
                       
                               sql= "SELECT id,nm,slr FROM emp WHERE id = "
                                    +msgout1+";";
                                 System.out.println("requet send id:" + sql);
                                 dout.writeUTF(sql);
                            }
                            else if ((!mes_txt1.getText().equals("")) && (!mes_txt2.getText().equals("")) && (mes_txt3.getText().equals("")) ) 
                             {
                                 sql= "SELECT id,nm,slr FROM emp WHERE(id ="
                                    +msgout1+" ) AND nm = '" + msgout2+ "' ;";
                                 System.out.println("requet sendid + Name: 12" + sql );
                                 dout.writeUTF(sql);
                             }
                 
                            else if ((!mes_txt2.getText().equals("")) && (!mes_txt3.getText().equals("")) && (mes_txt1.getText().equals("")) ) 
                                {                             
                                    sql= "SELECT * FROM emp WHERE nm LIKE '"
                                    +msgout2+"' AND slr = " + msgout3+ " ;";
                                 System.out.println("requet send Name + salary = " + sql );
                                 dout.writeUTF(sql);                                }
                                else if ((!mes_txt1.getText().equals("")) && (!mes_txt3.getText().equals("")) && (mes_txt2.getText().equals(""))) 
                                 {
                                    sql= "SELECT * FROM emp WHERE(id ="
                                    +msgout1+" ) AND slr = " + msgout3+ " ;";
                                 System.out.println("requet sendid + Name: 12" + sql );
                                 dout.writeUTF(sql);  
                                 }
                      
              }
        }
        }catch (Exception e){
            
        }
        
        
    }//GEN-LAST:event_selectbtnActionPerformed

    private void selectSUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSUMActionPerformed
        // TODO add your handling code here:
        
        
         try{
            
                    sql= "SELECT SUM(slr) FROM emp;";        
                    System.out.println("requet send:"+ sql );
                    dout.writeUTF(sql);
                   
         } catch (IOException ex) {
             Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_selectSUMActionPerformed

    private void creatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatActionPerformed
        // TODO add your handling code here:
        try{
            
                    sql= "CREATE TABLE emp(id INT PRIMARY KEY,nm VARCHAR(500) NOT NULL,slr double);";        
                    System.out.println("requet send:"+ sql );
                    dout.writeUTF(sql);
                   
         } catch (IOException ex) {
             Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_creatActionPerformed

    private void SelectOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectOrderActionPerformed

        try{
            
                    sql= "SELECT id,nm,slr FROM emp Order By slr;";        
                    System.out.println("requet send:"+ sql );
                    dout.writeUTF(sql);
                   
         } catch (IOException ex) {
             Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
    }//GEN-LAST:event_SelectOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
        try{
            s = new Socket("127.0.0.1",1201);
            din=new DataInputStream(s.getInputStream());
            dout=new DataOutputStream(s.getOutputStream());
            String msgin="";
            
            while(!msgin.equals("exit")){
                msgin=din.readUTF();
               // mes_s.append(mes_s.getText().trim()+"\n "+msgin);
               
            }
         
        } catch (Exception e) {
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SelectOrder;
    private javax.swing.JButton creat;
    private javax.swing.JButton delete;
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private static javax.swing.JTextField mes_txt1;
    private static javax.swing.JTextField mes_txt2;
    private static javax.swing.JTextField mes_txt3;
    private javax.swing.JButton selectSUM;
    private javax.swing.JButton selectbtn;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private boolean checkField(String field) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private long valueOf(String msgout3) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
